// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bs_errcode.proto

#ifndef PROTOBUF_bs_5ferrcode_2eproto__INCLUDED
#define PROTOBUF_bs_5ferrcode_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace bs_czl {
class MSG_RET;
class MSG_RETDefaultTypeInternal;
extern MSG_RETDefaultTypeInternal _MSG_RET_default_instance_;
}  // namespace bs_czl

namespace bs_czl {

namespace protobuf_bs_5ferrcode_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_bs_5ferrcode_2eproto

enum MSG_RET_ErrCode {
  MSG_RET_ErrCode_SUCCESS = 0,
  MSG_RET_ErrCode_FAIL = -1,
  MSG_RET_ErrCode_MSG_RET_ErrCode_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  MSG_RET_ErrCode_MSG_RET_ErrCode_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool MSG_RET_ErrCode_IsValid(int value);
const MSG_RET_ErrCode MSG_RET_ErrCode_ErrCode_MIN = MSG_RET_ErrCode_FAIL;
const MSG_RET_ErrCode MSG_RET_ErrCode_ErrCode_MAX = MSG_RET_ErrCode_SUCCESS;
const int MSG_RET_ErrCode_ErrCode_ARRAYSIZE = MSG_RET_ErrCode_ErrCode_MAX + 1;

const ::google::protobuf::EnumDescriptor* MSG_RET_ErrCode_descriptor();
inline const ::std::string& MSG_RET_ErrCode_Name(MSG_RET_ErrCode value) {
  return ::google::protobuf::internal::NameOfEnum(
    MSG_RET_ErrCode_descriptor(), value);
}
inline bool MSG_RET_ErrCode_Parse(
    const ::std::string& name, MSG_RET_ErrCode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MSG_RET_ErrCode>(
    MSG_RET_ErrCode_descriptor(), name, value);
}
// ===================================================================

class MSG_RET : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:bs_czl.MSG_RET) */ {
 public:
  MSG_RET();
  virtual ~MSG_RET();

  MSG_RET(const MSG_RET& from);

  inline MSG_RET& operator=(const MSG_RET& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MSG_RET& default_instance();

  static inline const MSG_RET* internal_default_instance() {
    return reinterpret_cast<const MSG_RET*>(
               &_MSG_RET_default_instance_);
  }

  void Swap(MSG_RET* other);

  // implements Message ----------------------------------------------

  inline MSG_RET* New() const PROTOBUF_FINAL { return New(NULL); }

  MSG_RET* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MSG_RET& from);
  void MergeFrom(const MSG_RET& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MSG_RET* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef MSG_RET_ErrCode ErrCode;
  static const ErrCode SUCCESS =
    MSG_RET_ErrCode_SUCCESS;
  static const ErrCode FAIL =
    MSG_RET_ErrCode_FAIL;
  static inline bool ErrCode_IsValid(int value) {
    return MSG_RET_ErrCode_IsValid(value);
  }
  static const ErrCode ErrCode_MIN =
    MSG_RET_ErrCode_ErrCode_MIN;
  static const ErrCode ErrCode_MAX =
    MSG_RET_ErrCode_ErrCode_MAX;
  static const int ErrCode_ARRAYSIZE =
    MSG_RET_ErrCode_ErrCode_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  ErrCode_descriptor() {
    return MSG_RET_ErrCode_descriptor();
  }
  static inline const ::std::string& ErrCode_Name(ErrCode value) {
    return MSG_RET_ErrCode_Name(value);
  }
  static inline bool ErrCode_Parse(const ::std::string& name,
      ErrCode* value) {
    return MSG_RET_ErrCode_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:bs_czl.MSG_RET)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct protobuf_bs_5ferrcode_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// MSG_RET

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace bs_czl

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::bs_czl::MSG_RET_ErrCode> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::bs_czl::MSG_RET_ErrCode>() {
  return ::bs_czl::MSG_RET_ErrCode_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_bs_5ferrcode_2eproto__INCLUDED
